import HashTable from "../05_哈希表HashTable/01_设计哈希表";

const hashTable = new HashTable()

console.log('---------put---------')
hashTable.put("aaa", 100)
hashTable.put("aaa", 200)
hashTable.put("bbb", 300)
hashTable.put("ccc", 400)
hashTable.put("abcq", 111)
hashTable.put("cbae7", 222)
console.log(hashTable.table)
console.log(hashTable.loadFactor)

hashTable.put("nba", 333)
hashTable.put("mba", 444)
hashTable.put("asdfwefgrgve", 444)
hashTable.put("adcvavvsbn33234Q", 444)
hashTable.put("zxCACVV", 444)
hashTable.put("QRBPI", 444)
hashTable.put("ggg", 444)
hashTable.put("QRBhgfPI", 444)
hashTable.put("urtyeh", 444)
hashTable.put("wqrwfvkl", 444)
console.log(hashTable.table)
console.log(hashTable.loadFactor)
console.log('---------delete---------')
hashTable.delete("nba")
hashTable.delete("mba")
hashTable.delete("abc")
hashTable.delete("cba")
hashTable.delete("aaa")
hashTable.delete("QRBhgfPI")
hashTable.delete("urtyeh")
hashTable.delete("wqrwfvkl")
console.log(hashTable.table)
console.log(hashTable.loadFactor)

console.log('----------clear--')
hashTable.clear()
console.log(hashTable.table)
console.log(hashTable.loadFactor)
hashTable.put("zz", 789)
hashTable.put("zz1", 800)
hashTable.put("zzz", 900)
console.log(hashTable.table)
console.log(hashTable.loadFactor)
